# Generated by Django 4.0.2 on 2022-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gIDNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.IntegerField(),
        ),
    ]
