# Generated by Django 4.0.2 on 2022-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_alter_student_gidnum_alter_student_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gIDNum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.CharField(max_length=10),
        ),
    ]
