# Generated by Django 4.0.2 on 2022-02-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_alter_student_dob_alter_student_gidnum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobileNumber',
            new_name='mobileNum',
        ),
    ]
