# Generated by Django 4.0.2 on 2022-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_rename_mobilenumber_student_mobilenum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuID',
            new_name='sid',
        ),
        migrations.RemoveField(
            model_name='vacdosestatus',
            name='vacID',
        ),
        migrations.RemoveField(
            model_name='vacdrive',
            name='vacID',
        ),
        migrations.AddField(
            model_name='vacdrive',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Completed')], default=1),
        ),
    ]
