# Generated by Django 4.0.2 on 2022-02-16 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_delete_vaccine_rename_stuid_student_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacdosestatus',
            name='vacDate',
        ),
        migrations.RemoveField(
            model_name='vacdosestatus',
            name='vacDoseNum',
        ),
        migrations.RemoveField(
            model_name='vacdrive',
            name='numDoses',
        ),
        migrations.AddField(
            model_name='student',
            name='vacPref',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Covaxin'), (2, 'Covishield')], default=0),
        ),
        migrations.AddField(
            model_name='vacdosestatus',
            name='vacDateD1',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacdosestatus',
            name='vacDateD2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacdosestatus',
            name='vacName',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Covaxin'), (2, 'Covishield')], default=0),
        ),
        migrations.AddField(
            model_name='vacdrive',
            name='numDosesC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacdrive',
            name='numDosesCS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='gIDType',
            field=models.IntegerField(choices=[(1, 'Aadhaar'), (2, 'Passport'), (3, 'Birth Cert')], default=1),
        ),
        migrations.AlterField(
            model_name='vacdrive',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Completed')], default=0),
        ),
    ]
