# Generated by Django 4.0.2 on 2022-02-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_remove_vacdosestatus_vacdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacdrive',
            name='id',
        ),
        migrations.AlterField(
            model_name='vacdosestatus',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vac_details', to='dbapp.student'),
        ),
        migrations.AlterField(
            model_name='vacdrive',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
