# Generated by Django 4.0.2 on 2022-02-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_rename_gidtype_student_gidtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gIDNum',
            new_name='gidno',
        ),
    ]
