# Generated by Django 4.0.2 on 2022-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_rename_gidnum_student_gidno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacdosestatus',
            name='vacDateD2',
            field=models.DateField(blank=True),
        ),
    ]
