# Generated by Django 4.0.2 on 2022-02-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_alter_vacdosestatus_vacdated2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacdosestatus',
            name='vacDateD2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
